name: .NET Core CI

on:
  push:
    branches:
      - main  # Trigger CI pipeline for pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger CI pipeline for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the repository code

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Specify the .NET version to use

    - name: Restore dependencies
      run: dotnet restore  # Restore project dependencies

    - name: Build the project
      run: dotnet build --configuration Release  # Build the project in Release configuration

    # - name: Run tests
    #   run: dotnet test --configuration Release  # Run tests on the project

    - name: Publish application (optional)
      run: dotnet publish --configuration Release --output ./publish  # Publish the app if needed for deployment
